apiVersion: v1
kind: Secret
metadata:
  name: rankup-notification-secret
  namespace: development
  labels:
    tier: backend
    app: rankup
data:
  DB_HOST: $DB_HOST
  DB_PORT: $DB_PORT
  DB_NAME: $DB_NAME
  DB_USERNAME: $DB_USERNAME
  DB_PASSWORD: $DB_PASSWORD
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rankup-configmap
  namespace: development
  labels:
    tier: backend
    app: rankup
data:
  APP_NAME: "RankUp"
  APP_ENV: "rank-up"
  APP_KEY: $APP_KEY
  # ... other environment variables
  GOOGLE_URL: $GOOGLE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-app-svc
  namespace: development
  annotations:
    external-dns.alpha.kubernetes.io/hostname: a33e856a9d97d495db1e9b19ce665885-654058732.us-east-1.elb.amazonaws.com
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: rankup
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rankup-deployment
  namespace: development
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: rankup
  template:
    metadata:
      annotations:
      labels:
        app: rankup
    spec:
      containers:
        - name: rankup-image
          image: hiralshah11199/rankup-app:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: rankup-configmap
            - secretRef:
                name: rankup-notification-secret
          ports:
            - containerPort: 9000
